name: Sync

on:
  schedule:
    - cron:  '0 18 * * 4'
    
  workflow_dispatch:  
  
jobs:
  start:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      UPSTREAM_REPOSITORY: ${{ secrets.WH }}
      TARGET_REPOSITORY: ${{ secrets.TR }}
      TARGET_BRANCH: ${{ secrets.WHB }}
      UPSTREAM_BRANCH: main
      
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${UPSTREAM_REPOSITORY}.git"
          upstream_dir=${UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git rm -r -f --cached .github
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "rm workflows"
          git push --force --follow-tags --tags "${target_repo}" "${UPSTREAM_BRANCH}:${TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"                

  sync:
    runs-on: ubuntu-latest
    needs: start
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      UPSTREAM_REPOSITORY: ${{ secrets.SX }}
      TARGET_REPOSITORY: ${{ secrets.TR }}
      TARGET_BRANCH: ${{ secrets.SXB }}
      UPSTREAM_BRANCH: main
 
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${UPSTREAM_REPOSITORY}.git"
          upstream_dir=${UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git push --force --follow-tags --tags "${target_repo}" "${UPSTREAM_BRANCH}:${TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"                

  over:
    runs-on: ubuntu-latest
    needs: [start,sync]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      UPSTREAM_REPOSITORY: ${{ secrets.SX }}
      TARGET_REPOSITORY: ${{ secrets.TR }}
      TARGET_BRANCH: ${{ secrets.NGB }}
      UPSTREAM_BRANCH: ${{ secrets.NGB }}
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${UPSTREAM_REPOSITORY}.git"
          upstream_dir=${UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git push --force --follow-tags --tags "${target_repo}" "${UPSTREAM_BRANCH}:${TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"  
